### ISSUE TITLE
Image-2-image in Colab Notebook

### ISSUE THREAD

**Issue by RobbeW** [camenduru/flux-jupyter#2]
First of all; thanks a lot for all the effort you put in adapting projects to fit within (Colab) Notebooks with such speed. Flux was barely one news cycle old and there was a Colab to try out. Thanks! 

Would it be possible to add a variable to the torch.inference lines to use the image2image pipeline that Flux has? The native repo contains a demo.py that references this capability of the model. 

Just a feature request.

**Comment by camenduru** [comment]
https://github.com/camenduru/flux-jupyter/blob/main/flux.1-dev-i2i_jupyter.ipynb
https://github.com/camenduru/flux-jupyter/blob/main/flux.1-schnell-i2i_jupyter.ipynb
