### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Rhaegar-dotcom** [camenduru/flux-jupyter#20]
Don t work ... Every time that i try a generation fail ... Appear error

**Comment by camenduru** [comment]
thanks for the info ❤ fixed

**Comment by Rhaegar-dotcom** [comment]
No the problem Is not resolved ... Fail every the generation and appear immediately error .. connection error

**Comment by Rhaegar-dotcom** [comment]
> thanks for the info ❤ fixed

No the problem Is not resolved ... Fail every the generation and appear immediately error .. connection error

**Comment by Rhaegar-dotcom** [comment]
Sorry but the problem still exists and other users are also complaining
about it, nothing has been fixed

Il dom 8 set 2024, 23:30 camenduru ***@***.***> ha scritto:
