### ISSUE TITLE
DON'T WORK BY MANY DAYS

### ISSUE THREAD

**Issue by Rhaegar-dotcom** [camenduru/flux-jupyter#24]
The link don t work by many days and there isn t answer by assistence ...

**Comment by marwanto606** [comment]
change gradio to 3.50.0 it work

**Comment by Rhaegar-dotcom** [comment]
> change gradio to 3.50.0 it work

How i can change gradio ? Can you explain me ?

**Comment by marwanto606** [comment]
change code
!pip install -q torchsde einops diffusers accelerate xformers==0.0.27.post2 gradio==4.32.0
ti
!pip install -q torchsde einops diffusers accelerate xformers==0.0.27.post2 gradio==3.50.0

**Comment by marwanto606** [comment]
or you can try my [article](https://www.marwanto606.com/2024/09/cara-menjalankan-flux-1-dev-realism-lora.html)
