### ISSUE TITLE
flux.1-dev-realism-lora-gradio_jupyter not working

### ISSUE THREAD

**Issue by Szakbal2001** [camenduru/flux-jupyter#26]
ERROR:fastapi:Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-98dc86e47754> in <cell line: 68>()
     66     return "/content/flux.png"
     67 
---> 68 with gr.Blocks(analytics_enabled=False) as demo:
     69     with gr.Row():
     70       with gr.Column():

10 frames
/usr/local/lib/python3.10/dist-packages/gradio/blocks.py in __exit__(self, exc_type, *args)
   1655             self.parent.children.extend(self.children)
   1656         self.config = self.get_config_file()
-> 1657         self.app = routes.App.create_app(self)
   1658         self.progress_tracking = any(block_fn.tracks_progress for block_fn in self.fns)
   1659         self.exited = True

/usr/local/lib/python3.10/dist-packages/gradio/routes.py in create_app(blocks, app_kwargs)
    267         @app.post("/login")
    268         @app.post("/login/")
--> 269         def login(form_data: OAuth2PasswordRequestForm = Depends()):
    270             username, password = form_data.username.strip(), form_data.password
    271             if app.auth is None:

/usr/local/lib/python3.10/dist-packages/fastapi/routing.py in decorator(func)
    992     ) -> Callable[[DecoratedCallable], DecoratedCallable]:
    993         def decorator(func: DecoratedCallable) -> DecoratedCallable:
--> 994             self.add_api_route(
    995                 path,
    996                 func,

/usr/local/lib/python3.10/dist-packages/fastapi/routing.py in add_api_route(self, path, endpoint, response_model, status_code, tags, dependencies, summary, description, response_description, responses, deprecated, methods, operation_id, response_model_include, response_model_exclude, response_model_by_alias, response_model_exclude_unset, response_model_exclude_defaults, response_model_exclude_none, include_in_schema, response_class, name, route_class_override, callbacks, openapi_extra, generate_unique_id_function)
    931             generate_unique_id_function, self.generate_unique_id_function
    932         )
--> 933         route = route_class(
    934             self.prefix + path,
    935             endpoint=endpoint,

/usr/local/lib/python3.10/dist-packages/fastapi/routing.py in __init__(self, path, endpoint, response_model, status_code, tags, dependencies, summary, description, response_description, responses, deprecated, name, methods, operation_id, response_model_include, response_model_exclude, response_model_by_alias, response_model_exclude_unset, response_model_exclude_defaults, response_model_exclude_none, include_in_schema, response_class, dependency_overrides_provider, callbacks, openapi_extra, generate_unique_id_function)
    552 
    553         assert callable(endpoint), "An endpoint must be a callable"
--> 554         self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
    555         for depends in self.dependencies[::-1]:
    556             self.dependant.dependencies.insert(

/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py in get_dependant(path, call, name, security_scopes, use_cache)
    282         )
    283         if param_details.depends is not None:
--> 284             sub_dependant = get_param_sub_dependant(
    285                 param_name=param_name,
    286                 depends=param_details.depends,

/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py in get_param_sub_dependant(param_name, depends, path, security_scopes)
    116 ) -> Dependant:
    117     assert depends.dependency
--> 118     return get_sub_dependant(
    119         depends=depends,
    120         dependency=depends.dependency,

/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py in get_sub_dependant(depends, dependency, path, name, security_scopes)
    152             security_scheme=dependency, scopes=use_scopes
    153         )
--> 154     sub_dependant = get_dependant(
    155         path=path,
    156         call=dependency,

/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py in get_dependant(path, call, name, security_scopes, use_cache)
    275     for param_name, param in signature_params.items():
    276         is_path_param = param_name in path_param_names
--> 277         param_details = analyze_param(
    278             param_name=param_name,
    279             annotation=param.annotation,

/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py in analyze_param(param_name, annotation, value, is_path_param)
    472         )
    473         if isinstance(field_info, params.Form):
--> 474             ensure_multipart_is_installed()
    475         if not field_info.alias and getattr(field_info, "convert_underscores", None):
    476             alias = param_name.replace("_", "-")

/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py in ensure_multipart_is_installed()
    105     except ImportError:
    106         logger.error(multipart_not_installed_error)
--> 107         raise RuntimeError(multipart_not_installed_error) from None
    108 
    109 

RuntimeError: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

**Comment by marwanto606** [comment]
add line
!pip install --upgrade python-multipart==0.0.12
