### ISSUE TITLE
BasicGuider vs. CFGGuider

### ISSUE THREAD

**Issue by rolux** [camenduru/flux-jupyter#4]
I'm wondering if there is a reason why this is using `BasicGuider` and not `CFGGuider`, which would allow for passing guidance scale?

**Comment by rolux** [comment]
https://comfyanonymous.github.io/ComfyUI_examples/flux/ says: "Make sure you set CFG to 1.0 when using it." ... so maybe I'm missing that this is a known limitation when using fp8?

**Comment by mannycalavera656** [comment]
Is there a way free VRAM after a render without starting over?

**Comment by rolux** [comment]
Was added in the latest lora notebook – consider this solved!
